// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNeoMlTQCY4bukXYt06k6cEB0dNmThyIA',
    appId: '1:1078708190038:web:6983d7d96467aa8a4034f7',
    messagingSenderId: '1078708190038',
    projectId: 'seekerai-504b9',
    authDomain: 'seekerai-504b9.firebaseapp.com',
    storageBucket: 'seekerai-504b9.firebasestorage.app',
    measurementId: 'G-DYWQY9BDZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMXQ77jFAneGMAgz7hx9VdvNpGTucvZL4',
    appId: '1:1078708190038:android:573acc96fd2be6bb4034f7',
    messagingSenderId: '1078708190038',
    projectId: 'seekerai-504b9',
    storageBucket: 'seekerai-504b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdqih9AEUDHBB410rHavFccO-FElSsNmM',
    appId: '1:1078708190038:ios:7d5a3fa61466404f4034f7',
    messagingSenderId: '1078708190038',
    projectId: 'seekerai-504b9',
    storageBucket: 'seekerai-504b9.firebasestorage.app',
    iosBundleId: 'com.example.seekauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNeoMlTQCY4bukXYt06k6cEB0dNmThyIA',
    appId: '1:1078708190038:web:40788b12889b79bb4034f7',
    messagingSenderId: '1078708190038',
    projectId: 'seekerai-504b9',
    authDomain: 'seekerai-504b9.firebaseapp.com',
    storageBucket: 'seekerai-504b9.firebasestorage.app',
    measurementId: 'G-71348JFLMN',
  );
}
